### ISSUE TITLE
User Defined Function Codes

### ISSUE THREAD

**Issue by apb2019** [yaacov/node-modbus-serial#258]
Could you add the ability to handle User Defined Function Codes (i.e. FC 65 to 72 and 100 to 110 decimal) as I would like to be able to send commands to a solar battery system that uses FC 66 (0x42) to control functions

**Comment by yaacov** [comment]
Hi,

Thanks for the issue :peach: , I do not implement new features at the moment due to lack of time :-(
But I do accept fixes and new features in the form of pull requests :exclamation: 

If you ( or someone you know ) want to implement this feature, and you wish to add it to the lib, please submit a pull request and link it to this issue.

p.s.
I also labelled this wit a `help wanted` label in case someone else will see it and want to help :heart: 

p.p.s
I will try to do it myself if I have the time, but don't wait for it ....

**Comment by apb2019** [comment]
Tx, unfortunately I don’t have the programming skills to do this myself. Hopefully someone may be able to take this on as I have yet to find any Modbus software that can handle user defined codes.

**Comment by yaacov** [comment]
Will be happy to get a pull request for that some day ... closing for now as stale.
